package tcc

type STATUS string

const (
	CREATED       STATUS = "CREATED"
	TRY_STARTED   STATUS = "TRY_STARTED"
	TRY_FAILED    STATUS = "TRY_FAILED"
	TRY_SUCCEEDED STATUS = "TRY_SUCCEEDED"

	COMMIT_STARTED   STATUS = "COMMIT_STARTED"
	COMMIT_FAILED    STATUS = "COMMIT_FAILED"
	COMMIT_SUCCEEDED STATUS = "COMMIT_SUCCEEDED"

	CANCEL_STARTED   STATUS = "CANCEL_STARTED"
	CANCEL_FAILED    STATUS = "CANCEL_FAILED"
	CANCEL_SUCCEEDED STATUS = "CANCEL_SUCCEEDED"
)

var status = [...]string{
	"CREATED",
	"TRY_STARTED",
	"TRY_FAILED",
	"TRY_SUCCEEDED",
	"COMMIT_STARTED",
	"COMMIT_FAILED",
	"COMMIT_SUCCEEDED",
	"CANCEL_STARTED",
	"CANCEL_FAILED",
	"CANCEL_SUCCEEDED",
}

func (s *STATUS) String() string {
	x := string(*s)
	for _, v := range status {
		if v == x {
			return x
		}
	}

	return ""
}
